### ISSUE TITLE
Subsystem Service fails to start

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#15]
I'm unable to subsystem-service to start without modifying the code:

```com.iris.bootstrap.BootstrapException: Error bootstrapping the injection context
        at com.iris.bootstrap.Bootstrap.bootstrap(Bootstrap.java:241)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:146)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:125)
        at com.iris.core.IrisApplication.main(IrisApplication.java:26)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.concurrent.ExecutorService annotated with @com.google.inject.name.Named(value=threadpool.incident) was bound.
  while locating java.util.concurrent.ExecutorService annotated with @com.google.inject.name.Named(value=threadpool.incident)
    for parameter 1 at com.iris.platform.subsystem.incident.AlarmIncidentServiceImpl.<init>(AlarmIncidentServiceImpl.java:55)
  at com.iris.platform.subsystem.incident.AlarmIncidentModule.configure(AlarmIncidentModule.java:44)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:225)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:327)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:394)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:348)
        at com.iris.bootstrap.Bootstrap.bootstrap(Bootstrap.java:239)
        ... 3 more
E0410 05:55:20.472   main c.i.core.IrisAbstractApplication] Application failed to start
com.iris.bootstrap.BootstrapException: Error bootstrapping the injection context
        at com.iris.bootstrap.Bootstrap.bootstrap(Bootstrap.java:241)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:146)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:125)
        at com.iris.core.IrisApplication.main(IrisApplication.java:26)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.concurrent.ExecutorService annotated with @com.google.inject.name.Named(value=threadpool.incident) was bound.
  while locating java.util.concurrent.ExecutorService annotated with @com.google.inject.name.Named(value=threadpool.incident)
    for parameter 1 at com.iris.platform.subsystem.incident.AlarmIncidentServiceImpl.<init>(AlarmIncidentServiceImpl.java:55)
  at com.iris.platform.subsystem.incident.AlarmIncidentModule.configure(AlarmIncidentModule.java:44)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:225)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:327)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:394)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:348)
        at com.iris.bootstrap.Bootstrap.bootstrap(Bootstrap.java:239)
        ... 3 common frames omitted

> Task :platform:arcus-containers:subsystem-service:runDocker FAILED

FAILURE: Build failed with an exception.
```

to work around this change I made the following change:

```
$ git diff platform/arcus-containers/subsystem-service/src/main/java/com/iris/platform/subsystem/incident/AlarmIncidentServiceImpl.java
diff --git a/platform/arcus-containers/subsystem-service/src/main/java/com/iris/platform/subsystem/incident/AlarmIncidentServiceImpl.java b/platform/arcus-containers/subsystem-service/src/main/java/com/iris/platform/subsystem/incident/AlarmIncidentServiceImpl.java
index 7e88736..15eb40d 100644
--- a/platform/arcus-containers/subsystem-service/src/main/java/com/iris/platform/subsystem/incident/AlarmIncidentServiceImpl.java
+++ b/platform/arcus-containers/subsystem-service/src/main/java/com/iris/platform/subsystem/incident/AlarmIncidentServiceImpl.java
@@ -16,6 +16,7 @@
 package com.iris.platform.subsystem.incident;
 
 import java.util.concurrent.ExecutorService;
+import java.util.concurrent.ForkJoinPool;
 
 import com.google.inject.Inject;
 import com.google.inject.Singleton;
@@ -43,7 +44,7 @@ public class AlarmIncidentServiceImpl extends AbstractPlatformService {
    @Inject
    public AlarmIncidentServiceImpl(
          PlatformMessageBus platformBus,
-         @Named(NAME_EXECUTOR_POOL) ExecutorService executor,
+         ForkJoinPool executor,
          SubsystemExecutorResolver subsystemExecutorResolver,
          PlatformDispatcherFactory dispatcherFactory,
          GetAttributesHandler getAttributesHandler,
```

How do I inject threadpool.incident?

**Comment by nicholasstudt** [comment]
There appears to be a missing configuration option, NAME_EXECUTOR_POOL appears to not have a proper default.

**Comment by AndrewX192** [comment]
Yes, that's what I thought too.. but unfortunately setting 
`threadpool.incident=java.util.concurrent.ForkJoinPool` in `./platform/arcus-containers/subsystem-service/src/dist/conf/subsystem-service.properties` hasn't worked. I can't figure out the right place to inject this ExecutorService. Any advice on where to configure it?

**Comment by AndrewX192** [comment]
Unfortunately I'm going to need help on this one - I'm stumped on how to inject java.util.concurrent.ForkJoinPool with Guice from the properties file, and I can't find any example of how it was done in the past (e.g. there's no other examples in the code). Furthermore, I don't see a good way to default this to something like ForkJoinPool but still allow threadpool.incident/NAME_EXECUTOR_POOL to be set. I'm going to proceed with this hard coded in my branch for now, until someone with more familiarity with the project can advise.

**Comment by AndrewX192** [comment]
Will close as soon as #35 lands, for now if anyone runs into this issue they will need to manually apply that patch.

**Comment by AndrewX192** [comment]
Fix has landed.
