### ISSUE TITLE
Write up directions for old improper schema

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#153]
The old schema that gets generated is not properly formed and will need some retroactive corrections:

```
Expected checksum d2b8cc758e009a06f20c4d41e7382287, but got checksum f45d6346c97fac4b3c1422c8c779249e for change set personTable

com.iris.modelmanager.changelog.checksum.ChecksumInvalidException: Expected checksum d2b8cc758e009a06f20c4d41e7382287, but got checksum f45d6346c97fac4b3c1422c8c779249e for change set personTable
	at com.iris.modelmanager.changelog.checksum.ChecksumUtil.verifyChecksums(ChecksumUtil.java:57)
	at com.iris.modelmanager.changelog.ChangeLogSet.verify(ChangeLogSet.java:123)
	at com.iris.modelmanager.changelog.ChangeLogSet.verify(ChangeLogSet.java:111)
	at com.iris.modelmanager.engine.ExecutionEngine.execute(ExecutionEngine.java:71)
	at com.iris.modelmanager.ModelManager.start(ModelManager.java:42)
	at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:185)
	at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:126)
	at com.iris.modelmanager.ModelManager.main(ModelManager.java:46)
00:29:33.507 [main] ERROR c.iris.core.IrisAbstractApplication - Application failed to start
com.iris.modelmanager.changelog.checksum.ChecksumInvalidException: Expected checksum d2b8cc758e009a06f20c4d41e7382287, but got checksum f45d6346c97fac4b3c1422c8c779249e for change set personTable
	at com.iris.modelmanager.changelog.checksum.ChecksumUtil.verifyChecksums(ChecksumUtil.java:57)
	at com.iris.modelmanager.changelog.ChangeLogSet.verify(ChangeLogSet.java:123)
	at com.iris.modelmanager.changelog.ChangeLogSet.verify(ChangeLogSet.java:111)
	at com.iris.modelmanager.engine.ExecutionEngine.execute(ExecutionEngine.java:71)
	at com.iris.modelmanager.ModelManager.start(ModelManager.java:42)
	at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:185)
	at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:126)
	at com.iris.modelmanager.ModelManager.main(ModelManager.java:46)
Shutting down...
```

**Comment by AndrewX192** [comment]
Temporary database-only fixes:
```
update production.changeset set checksum='f45d6346c97fac4b3c1422c8c779249e' where id='rob:personTable';
update production.changeset set checksum='791d4a62617ff05ada33b79de8acf1e5' where id='jboardman:deviceTable';
update production.changeset set checksum='46f6e514abbddacc2af8f50e6fc053ca' where id='tweidling:ruleEnvironmentTable';
```
