### ISSUE TITLE
Null Execption with Model Manager History

### ISSUE THREAD

**Issue by jsb145** [arcus-smart-home/arcusplatform#21]
When running start up getting the following error in model manager module.  In previous changes services was commented out.  
 

       arcus-modelmanager v2018.10.2 [application directory: /home/jsb145/arcusplatform/platform/arcus-modelmanager/build/install/modelmanager]
null

java.lang.NullPointerException
        at com.iris.modelmanager.engine.ExecutionEngine.createSession(ExecutionEngine.java:193)
        at com.iris.modelmanager.engine.ExecutionEngine.<init>(ExecutionEngine.java:54)
        at com.iris.modelmanager.ModelManager.start(ModelManager.java:41)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:181)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:125)
        at com.iris.modelmanager.ModelManager.main(ModelManager.java:46)
07:33:01.304 [main] ERROR c.iris.core.IrisAbstractApplication - Application failed to start
java.lang.NullPointerException: null
        at com.iris.modelmanager.engine.ExecutionEngine.createSession(ExecutionEngine.java:193)
        at com.iris.modelmanager.engine.ExecutionEngine.<init>(ExecutionEngine.java:54)
        at com.iris.modelmanager.ModelManager.start(ModelManager.java:41)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:181)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:125)
        at com.iris.modelmanager.ModelManager.main(ModelManager.java:46)
Shutting down...
07:33:01.307 [Thread-1] INFO  com.iris.bootstrap.ServiceLocator - Received shutdown signal, shutting down modules
07:33:01.307 [Thread-1] INFO  com.iris.bootstrap.ServiceLocator - Shutdown

> Task :platform:arcus-modelmanager:run-history FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platform:arcus-modelmanager:run-history'.
> Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/bin/java'' finished with non-zero exit value 1

**Comment by AndrewX192** [comment]
Although that error isn't too helpful, I don't think it's an issue in the code, but rather perhaps that zookeeper or cassandra isn't working. Could you double check that those services are running and that the logs are free of obvious errors?

**Comment by jsb145** [comment]
I have not found anything unusual in the logs.  The following is the output from the start up.
+ docker_exec eyeris-cassandra cassandra-cmd setup
+ docker_exec eyeris-kafka kafka-cmd setup
+ docker exec eyeris-cassandra cassandra-cmd setup
+ docker exec eyeris-kafka kafka-cmd setup
adding kafka-provision topics
Kafka appears to already be provisioned, exiting...
adding kafka-operations-provision topics
Kafka appears to already be provisioned, exiting...
Cassandra is online
Creating keyspace dev
<stdin>:2:AlreadyExists: Keyspace 'dev' already exists
Creating support keyspace support
<stdin>:2:AlreadyExists: Keyspace 'support' already exists
Creating video keyspace video
<stdin>:2:AlreadyExists: Keyspace 'video' already exists
Creating history keyspace history
<stdin>:2:AlreadyExists: Keyspace 'history' already exists
Creating analytics keyspace analytics
<stdin>:2:AlreadyExists: Keyspace 'analytics' already exists
+ sleep 2

I went thru and cleaned up docker to make sure it was clean.  Both Zookeeper and Cassandra up and running.

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                      NAMES
c25c2a3d0645        eyeris/kafka        "/usr/bin/kafka-cmd …"   About an hour ago   Up About an hour    0.0.0.0:9092->9092/tcp                                                                                     eyeris-kafka
a88b98e6a017        eyeris/cassandra    "/usr/bin/cassandra-…"   About an hour ago   Up About an hour    0.0.0.0:7000-7001->7000-7001/tcp, 0.0.0.0:7199->7199/tcp, 0.0.0.0:9042->9042/tcp, 0.0.0.0:9160->9160/tcp   eyeris-cassandra
9f407be0e2e8        eyeris/zookeeper    "/usr/bin/zookeeper-…"   About an hour ago   Up About an hour    0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp                                     eyeris-zookeeper

**Comment by AndrewX192** [comment]
Looking at that code, it would suggest that you don't have any contactpoints defined. Perhaps that's because of your /etc/hosts file or perhaps that's because the dev keyspace doesn't exist

Can you try both of the following (one at a time) and report back?

* Review platform/arcus-modelmanager/README.md and attempt to create the dev schema (NOTE: in my experience I am able to run cqlsh in docker, so your experience may vary)
* Attempt to adjust your /etc/hosts file, and add something along the lines of `127.0.0.1	cassandra.eyeris kafkaops.eyeris kairosops.eyeris kafka.eyeris`

Please report back if either of these helped. I want to get https://github.com/wl-net/arcusplatform/blob/master/docs/quickstart.md up to date.

**Comment by TheEssemCraft** [comment]
I'm having a similar problem, however unlike OP, I get this output when it runs those exec commands:
```
+ docker_exec eyeris-kafka kafka-cmd setup
+ docker exec eyeris-kafka kafka-cmd setup
+ docker_exec eyeris-cassandra cassandra-cmd setup
+ docker exec eyeris-cassandra cassandra-cmd setup
Error response from daemon: Container fb10a77ce2269af21f40d5ba4dbd16e12ec0bc3a264b7b9812bb0af5d28b8627 is not running
Error response from daemon: Container 920627633feeaceb3e8d5ed814cbec88a9d145016b54fdc29db63fbaadb4a21e is not running
```

**Comment by AndrewX192** [comment]
That appears to be the result of kafka and cassandra not starting. Unfortunately the startPlatform scripts can only be run once - once you've run them, you'll need to clean up and potentially remove the containers before you can call those scripts again. Please note that removing cassandra will result in data loss if you already had a hub/account setup in Arcus.

**Comment by TheEssemCraft** [comment]
So I ended up running the build process in a new VM and eventually got to a similar contactpoints issue. I can confirm that adding that line to the hosts file fixed it.

**Comment by AndrewX192** [comment]
Closing due to inactivity
