### ISSUE TITLE
Can't customize devices when pairing

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#38]
When pairing, the user is prompted to configure any paired devices. This will unfortunately fail due to the following error:
```
D0501 03:56:53.944 p-1799  com.iris.messages.errors.Errors] Translating exception
java.lang.IllegalArgumentException: Could not load type [interface com.iris.platform.subsystem.SubsystemDao]: Could not load type [interface com.iris.platform.subsystem.SubsystemDao]: Guice configuration errors:

1) No implementation for com.iris.platform.subsystem.SubsystemDao was bound.
  while locating com.iris.platform.subsystem.SubsystemDao

1 error
	at com.iris.bootstrap.ServiceLocator.getInstance(ServiceLocator.java:80)
	at com.iris.platform.pairing.customization.SecurityModeCustomization.apply(SecurityModeCustomization.java:60)
	at com.iris.platform.pairing.customization.PairingCustomization.toStepIf(PairingCustomization.java:136)
	at com.iris.platform.pairing.customization.PairingCustomizationManager.lambda$apply$0(PairingCustomizationManager.java:101)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.iris.platform.pairing.customization.PairingCustomizationManager.apply(PairingCustomizationManager.java:103)
	at com.iris.platform.pairing.handler.CustomizeRequestHandler.customize(CustomizeRequestHandler.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.iris.reflection.MethodInvoker.apply(MethodInvoker.java:59)
	at com.iris.core.platform.RequestResponseMessageBus.invoke(RequestResponseMessageBus.java:73)
	at com.iris.core.platform.RequestResponseMessageBus.invokeAndSendResponse(RequestResponseMessageBus.java:43)
	at com.iris.core.platform.PlatformDispatcher.handleRequest(PlatformDispatcher.java:81)
	at com.iris.core.platform.PlatformDispatcher.onMessage(PlatformDispatcher.java:74)
	at com.iris.core.platform.PlatformDispatcher.onMessage(PlatformDispatcher.java:36)
	at com.iris.executor.PlaceExecutor.lambda$null$0(PlaceExecutor.java:96)
	at com.iris.executor.TaskQueue$RunnableFuture.run(TaskQueue.java:200)
	at com.iris.executor.TaskQueue.dispatch(TaskQueue.java:129)
	at com.iris.util.MdcAwareRunnable.run(MdcAwareRunnable.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Could not load type [interface com.iris.platform.subsystem.SubsystemDao]: Guice configuration errors:

1) No implementation for com.iris.platform.subsystem.SubsystemDao was bound.
  while locating com.iris.platform.subsystem.SubsystemDao

1 error
	at com.iris.bootstrap.guice.GuiceServiceLocator.getInstance(GuiceServiceLocator.java:81)
	at com.iris.bootstrap.ServiceLocator.getInstance(ServiceLocator.java:78)
	... 29 common frames omitted
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for com.iris.platform.subsystem.SubsystemDao was bound.
  while locating com.iris.platform.subsystem.SubsystemDao

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1035)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at com.iris.bootstrap.guice.GuiceServiceLocator.getInstance(GuiceServiceLocator.java:79)
	... 30 common frames omitted
D0501 03:56:53.944 p-1799    c.i.c.m.kafka.KafkaMessageBus] Sending message [PlatformMessage [value=ErrorEvent [code=IllegalArgumentException, message=Could not load type [interface com.iris.platform.subsystem.SubsystemDao]: Could not load type [interface com.iris.platform.subsystem.SubsystemDao]: Guice configuration errors:

1) No implementation for com.iris.platform.subsystem.SubsystemDao was bound.
  while locating com.iris.platform.subsystem.SubsystemDao
```

The following fix fixes this

```
$ git diff platform/arcus-lib/src/main/java/com/iris/platform/pairing/customization/SecurityModeCustomization.java
diff --git a/platform/arcus-lib/src/main/java/com/iris/platform/pairing/customization/SecurityModeCustomization.java b/platform/arcus-lib/src/main/java/com/iris/platform/pairing/customization/SecurityModeCustomization.java
index bcab9e2..75cd456 100644
--- a/platform/arcus-lib/src/main/java/com/iris/platform/pairing/customization/SecurityModeCustomization.java
+++ b/platform/arcus-lib/src/main/java/com/iris/platform/pairing/customization/SecurityModeCustomization.java
@@ -27,6 +27,7 @@ import com.iris.messages.model.Place;
 import com.iris.messages.model.serv.AlarmModel;
 import com.iris.platform.model.ModelEntity;
 import com.iris.platform.subsystem.SubsystemDao;
+import com.iris.platform.subsystem.cassandra.CassandraSubsystemDao;
 
 class SecurityModeCustomization extends PairingCustomization {
        
@@ -57,7 +58,7 @@ class SecurityModeCustomization extends PairingCustomization {
                // FIXME inject the subsystem dao
                ModelEntity entity =
                                ServiceLocator
-                                       .getInstance(SubsystemDao.class)
+                                       .getInstance(CassandraSubsystemDao.class) //CassandraSubsystemDao.class
                                        .findByPlaceAndNamespace(place.getId(), AlarmSubsystemCapability.NAMESPACE);
                return AlarmModel.getDevices(AlarmSubsystemCapability.ACTIVEALERTS_SECURITY, entity, ImmutableSet.of()).contains(device.getAddress().getRepresentation());
        }
```

**Comment by AndrewX192** [comment]
Fixed in #93
