### ISSUE TITLE
arcus-modelmanager support-resources missing

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#6]
It appears that there's a dependency on support-resources existing, but it wasn't released as part of arcus. Probably need to remove this dependency 
```
11:22:20.959 [main] INFO  c.iris.core.IrisAbstractApplication - starting configured application:
        arcus-modelmanager v2018.10.2 [application directory: /home/wlnet/arcusplatform/platform/arcus-modelmanager/build/install/modelmanager]
Home directory not found @ /home/wlnet/arcusplatform/platform/arcus-modelmanager/src/dist/support-resources

java.lang.IllegalArgumentException: Home directory not found @ /home/wlnet/arcusplatform/platform/arcus-modelmanager/src/dist/support-resources
        at com.iris.modelmanager.context.ManagerContext$Builder.validateHomeDirectory(ManagerContext.java:96)
        at com.iris.modelmanager.context.ManagerContext$Builder.build(ManagerContext.java:77)
        at com.iris.modelmanager.ModelManager.createContext(ModelManager.java:51)
        at com.iris.modelmanager.ModelManager.start(ModelManager.java:41)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:181)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:125)
        at com.iris.modelmanager.ModelManager.main(ModelManager.java:46)
11:22:20.961 [main] ERROR c.iris.core.IrisAbstractApplication - Application failed to start
java.lang.IllegalArgumentException: Home directory not found @ /home/wlnet/arcusplatform/platform/arcus-modelmanager/src/dist/support-resources
        at com.iris.modelmanager.context.ManagerContext$Builder.validateHomeDirectory(ManagerContext.java:96)
        at com.iris.modelmanager.context.ManagerContext$Builder.build(ManagerContext.java:77)
        at com.iris.modelmanager.ModelManager.createContext(ModelManager.java:51)
        at com.iris.modelmanager.ModelManager.start(ModelManager.java:41)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:181)
        at com.iris.core.IrisAbstractApplication.exec(IrisAbstractApplication.java:125)
        at com.iris.modelmanager.ModelManager.main(ModelManager.java:46)
Shutting down...
11:22:20.962 [Thread-1] INFO  com.iris.bootstrap.ServiceLocator - Received shutdown signal, shutting down modules
11:22:20.963 [Thread-1] INFO  c.i.c.m.r.IrisMetricsTopicReporter - Stopping topics reporter
11:22:21.041 [Thread-1] INFO  o.a.k.clients.producer.KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
11:22:53.314 [Thread-1] INFO  com.iris.bootstrap.ServiceLocator - Shutdown

> Task :platform:arcus-modelmanager:run-support FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platform:arcus-modelmanager:run-support'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 56s
70 actionable tasks: 16 executed, 54 up-to-date
```

**Comment by AndrewX192** [comment]
Solution seems to be just to remove the support schema from the build file, see https://github.com/wl-net/arcusplatform/commit/284de932bac8f6b5db80fb6f4005e175e8084bc7

**Comment by AndrewX192** [comment]
I haven't seem this come up recently, so I'm going to close it - I believe it was fixed in one of my earlier pull requests.
