### ISSUE TITLE
Oculus fails to load configuration, throws NullPointerException instead of showing login screen

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#9]
Expected behavior: `./gradlew :tools:oculus:run` results in Oculus opening.
Actual behavior: program opens, shows "loading configuration" and disappears.

Full exception stack:
```
> Task :tools:oculus:run
22:20:49.844 [main] WARN  c.n.g.lifecycle.ClasspathScanner - No base packages specified - no classpath scanning will be done
22:20:51.882 [main] WARN  com.iris.oculus.Main - Uncaught Exception
java.lang.reflect.InvocationTargetException: null
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
        at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
        at com.iris.oculus.Main.main(Main.java:267)
Caused by: java.lang.NullPointerException: null
        at com.iris.oculus.modules.session.SessionController.getLastSession(SessionController.java:630)
        at com.iris.oculus.modules.session.SessionController.login(SessionController.java:254)
        at com.iris.oculus.Main.lambda$main$7(Main.java:304)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
22:20:51.882 [main] WARN  com.iris.oculus.Application - Uncaught Exception
java.lang.reflect.InvocationTargetException: null
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
        at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
        at com.iris.oculus.Main.main(Main.java:267)
Caused by: java.lang.NullPointerException: null
        at com.iris.oculus.modules.session.SessionController.getLastSession(SessionController.java:630)
        at com.iris.oculus.modules.session.SessionController.login(SessionController.java:254)
        at com.iris.oculus.Main.lambda$main$7(Main.java:304)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
<============-> 99% EXECUTING [12s]
```

This can be fixed by a simple null check in tools/oculus/src/main/java/com/iris/oculus/modules/session/SessionController.java

**Comment by AndrewX192** [comment]
Fixed in https://github.com/wl-net/arcusplatform/commit/5d8da94a08771a4e2f06ea699dcf1577e59a7330

**Comment by msilvermanks** [comment]
Thanks, nice catch. If you wanna make a PR for master here I can merge this in

**Comment by AndrewX192** [comment]
Closing, since this should be resolved in the pull request.
